server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,heapdump,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      # If the app runs on your host and Jaeger runs via Docker on the same machine:
      endpoint: http://localhost:9411/api/v2/spans
      # If the app runs in Docker on the same network as Jaeger, change to:
      # endpoint: http://jaeger:9411/api/v2/spans

logging:
  level:
    io.micrometer: INFO
# No fragile logging.pattern here; your logback-spring.xml already injects trace/span.
